ontology:
  stage:
    pyrolysis: ["pyrolysis", "pyroly", "thermal decomposition", "热解", "热分解", "热裂解", "干馏"]
    gasification: ["gasification", "gasify", "气化", "气化反应"]
    coupled: ["coupled", "coupling", "combined", "co-processing", "耦合", "联立", "联合", "复合"]
    oxidation: ["oxidation", "oxidize", "partial oxidation", "氧化", "氧化反应", "部分氧化"]
    combustion: ["combustion", "burning", "燃烧", "燃烧反应"]
    ignition: ["ignition", "ignited", "点火", "着火", "着火特性"]

  gas_agent:
    steam: ["steam", "water vapor", "water vapour", "蒸汽", "水蒸气", "H2O", "H₂O"]
    o2: ["o2", "O2", "O₂", "oxygen", "氧气", "纯氧"]
    air: ["air", "空气", "air atmosphere", "空气气氛"]
    co2: ["co2", "CO2", "CO₂", "carbon dioxide", "二氧化碳"]
    n2: ["n2", "N2", "N₂", "nitrogen", "氮气"]

  pollutants:
    NH3: ["NH3", "NH₃", "ammonia", "氨"]
    HCN: ["HCN", "hydrogen cyanide", "氰化氢"]
    NOx: ["NOx", "NOX", "NOₓ", "nox", "nitrogen oxides", "氮氧化物"]
    H2S: ["H2S", "H₂S", "hydrogen sulfide", "硫化氢"]
    SO2: ["SO2", "SO₂", "sulfur dioxide", "二氧化硫"]
    COS: ["COS", "carbonyl sulfide", "carbonylsulfide", "羰基硫"]
    benzene: ["benzene", "C6H6", "C₆H₆", "苯"]
    phenols: ["phenol", "phenols", "phenolic", "phenolics", "酚", "酚类", "酚类物质"]
